version: 2

models:
  - name: stg_salesforce_customers
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null

  - name: stg_square_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null

  - name: stg_salesforce_trucks
    columns:
      - name: truck_id
        data_tests:
          - unique
          - not_null
      - name: make
        data_tests:
          - accepted_values:
              arguments:
                values: ['Airstream',
                         'Chevrolet',
                         'Custom',
                         'Citroen',
                         'Ford',
                         'Freightliner',
                         'Nissan',
                         'Volkswagen']